
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: RaConf'16
subtitle: "RaConf 16"
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site
url: "http://raconf.sausiber.org" # the base hostname & protocol for your site
baseurl: ""
cover: "/img/pp.jpg"
logo: "/img/pp.jpg"

# Build settings
markdown: kramdown

# Google analytics
ga_tracking_id: "UA-86185304-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
